### ISSUE TITLE
Stock history   

### ISSUE THREAD

**Issue by aymen3009** [StockManagementLabs/atum-stock-manager-for-woocommerce#14]
Hello, I want to ask if is there a way to get the stock at a specific date. I am creating a monthly report and I need the stock at the beginning of that month and at the end. Does ATUM keeps logs and/or history details about the inventory?

**Comment by smachi** [comment]
Hi @aymen3009 

For support questions, use our official forums:
https://forum.stockmanagementlabs.com/

Thank you
